---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.0.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.0.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.0.0
  i386: ghcr.io/hassio-addons/debian-base/i386:6.0.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
